set-option -g default-shell /opt/homebrew/bin/fish
unbind C-b
set-option -g prefix C-Space
bind C-Space send-prefix

# Use vi keys in copy mode
set-option -g mode-keys vi

# Use vi keys for pane navigation
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection
bind-key -T copy-mode-vi Escape send-keys -X cancel

# Use space to enter visual mode (copy)
bind Space copy-mode -u
