[window]
opacity = 0.97
startup_mode = "Maximized"
decorations = "none"

[colors.primary]
background = "#1e1e1e"
foreground = "#d4d4d4"

[terminal]

[terminal.shell]
program = "/usr/bin/fish"
args = ["--login"]

[colors.cursor]
text = "CellBackground"
cursor = "#ffc743"  # gruvbox yellow

